import mongoose from "mongoose";
import Habit from "../models/HabitSchema.js";

/**
 * Predefined habits grouped by category.
 * Each has:
 * - key: MUST match what your AI model expects (HABIT_LABEL_MAP key)
 * - habitName: user-facing name
 * - label: slightly more descriptive label for UI
 * - icon: MaterialCommunityIcons name (for dashboard & camera modal)
 * - defaultTime: default display time
 * - timeSlot: "morning" | "afternoon" | "evening" | "night"
 * - group: high-level category for UI grouping
 */

export const HABIT_DEFS = [
  // ---------------- MOVEMENT / FITNESS ----------------
  { key: "pushups", habitName: "Push-ups", label: "Do push-ups", icon: "arm-flex", defaultTime: "07:00 AM", timeSlot: "morning", group: "Movement / Fitness" },
  { key: "pullups", habitName: "Pull-ups", label: "Do pull-ups", icon: "weight-lifter", defaultTime: "07:00 AM", timeSlot: "morning", group: "Movement / Fitness" },
  { key: "situps", habitName: "Sit-ups", label: "Do sit-ups", icon: "recline", defaultTime: "07:00 AM", timeSlot: "morning", group: "Movement / Fitness" },
  { key: "plank", habitName: "Plank", label: "Hold a plank", icon: "human-handsup", defaultTime: "07:05 AM", timeSlot: "morning", group: "Movement / Fitness" },
  { key: "squats", habitName: "Squats", label: "Do bodyweight squats", icon: "human-handsdown", defaultTime: "07:10 AM", timeSlot: "morning", group: "Movement / Fitness" },
  { key: "lunges", habitName: "Lunges", label: "Do lunges", icon: "human", defaultTime: "07:15 AM", timeSlot: "morning", group: "Movement / Fitness" },
  { key: "deadlifts", habitName: "Deadlifts", label: "Do deadlifts", icon: "weight-lifter", defaultTime: "07:20 AM", timeSlot: "morning", group: "Movement / Fitness" },
  { key: "bench_press", habitName: "Bench Press", label: "Bench press workout", icon: "weight-lifter", defaultTime: "07:25 AM", timeSlot: "morning", group: "Movement / Fitness" },
  { key: "yoga", habitName: "Yoga", label: "Do yoga session", icon: "yoga", defaultTime: "06:30 AM", timeSlot: "morning", group: "Movement / Fitness" },
  { key: "meditation", habitName: "Meditation", label: "Meditate", icon: "meditation", defaultTime: "09:00 PM", timeSlot: "night", group: "Movement / Fitness" },
  { key: "running", habitName: "Running", label: "Go for a run", icon: "run", defaultTime: "06:30 AM", timeSlot: "morning", group: "Movement / Fitness" },
  { key: "jogging", habitName: "Jogging", label: "Go for a jog", icon: "run", defaultTime: "06:40 AM", timeSlot: "morning", group: "Movement / Fitness" },
  { key: "walking", habitName: "Walking", label: "Go for a walk", icon: "walk", defaultTime: "06:30 PM", timeSlot: "evening", group: "Movement / Fitness" },
  { key: "cycling", habitName: "Cycling", label: "Go cycling", icon: "bike", defaultTime: "07:00 AM", timeSlot: "morning", group: "Movement / Fitness" },
  { key: "swimming", habitName: "Swimming", label: "Go swimming", icon: "swim", defaultTime: "05:00 PM", timeSlot: "evening", group: "Movement / Fitness" },
  { key: "jump_rope", habitName: "Jump Rope", label: "Jump rope", icon: "jump-rope", defaultTime: "07:30 AM", timeSlot: "morning", group: "Movement / Fitness" },
  { key: "stretching", habitName: "Stretching", label: "Do stretching routine", icon: "human-handsup", defaultTime: "08:00 AM", timeSlot: "morning", group: "Movement / Fitness" },
  { key: "tai_chi", habitName: "Tai Chi", label: "Practice Tai Chi", icon: "yin-yang", defaultTime: "07:45 AM", timeSlot: "morning", group: "Movement / Fitness" },
  { key: "football", habitName: "Football", label: "Play football", icon: "football", defaultTime: "05:00 PM", timeSlot: "evening", group: "Movement / Fitness" },
  { key: "basketball", habitName: "Basketball", label: "Play basketball", icon: "basketball-hoop", defaultTime: "05:30 PM", timeSlot: "evening", group: "Movement / Fitness" },
  { key: "tennis", habitName: "Tennis", label: "Play tennis", icon: "tennis", defaultTime: "06:00 PM", timeSlot: "evening", group: "Movement / Fitness" },
  { key: "badminton", habitName: "Badminton", label: "Play badminton", icon: "badminton", defaultTime: "06:30 PM", timeSlot: "evening", group: "Movement / Fitness" },
  { key: "table_tennis", habitName: "Table Tennis", label: "Play table tennis", icon: "table-tennis", defaultTime: "07:00 PM", timeSlot: "evening", group: "Movement / Fitness" },
  { key: "boxing", habitName: "Boxing", label: "Boxing practice", icon: "boxing-glove", defaultTime: "07:30 PM", timeSlot: "evening", group: "Movement / Fitness" },
  { key: "martial_arts", habitName: "Martial Arts", label: "Practice martial arts", icon: "karate", defaultTime: "08:00 PM", timeSlot: "evening", group: "Movement / Fitness" },
  { key: "dance_practice", habitName: "Dance Practice", label: "Practice dancing", icon: "dance-ballroom", defaultTime: "08:30 PM", timeSlot: "evening", group: "Movement / Fitness" },
  { key: "mountain_climbing", habitName: "Mountain Climbing", label: "Go mountain climbing", icon: "mountain", defaultTime: "08:00 AM", timeSlot: "morning", group: "Movement / Fitness" },
  { key: "canoeing", habitName: "Canoeing", label: "Go canoeing", icon: "kayak", defaultTime: "10:00 AM", timeSlot: "morning", group: "Movement / Fitness" },
  { key: "skating", habitName: "Skating", label: "Roller skating", icon: "roller-skate", defaultTime: "11:00 AM", timeSlot: "morning", group: "Movement / Fitness" },
  { key: "parkour", habitName: "Parkour", label: "Practice parkour", icon: "run-fast", defaultTime: "01:00 PM", timeSlot: "afternoon", group: "Movement / Fitness" },
  { key: "hiking", habitName: "Hiking", label: "Go hiking", icon: "hiking", defaultTime: "03:30 PM", timeSlot: "afternoon", group: "Movement / Fitness" },
  { key: "pilates", habitName: "Pilates", label: "Do pilates", icon: "roll", defaultTime: "06:00 PM", timeSlot: "evening", group: "Movement / Fitness" },
  { key: "calisthenics", habitName: "Calisthenics", label: "Calisthenics workout", icon: "human", defaultTime: "07:00 AM", timeSlot: "morning", group: "Movement / Fitness" },
  { key: "surfing", habitName: "Surfing", label: "Go surfing", icon: "surf", defaultTime: "08:00 AM", timeSlot: "morning", group: "Movement / Fitness" },
  { key: "climbing", habitName: "Climbing", label: "Go climbing", icon: "mountain", defaultTime: "02:00 PM", timeSlot: "afternoon", group: "Movement / Fitness" },
  { key: "obstacle_course", habitName: "Obstacle Course", label: "Do obstacle course", icon: "run-fast", defaultTime: "11:00 AM", timeSlot: "morning", group: "Movement / Fitness" },
  { key: "gymnastics", habitName: "Gymnastics", label: "Practice gymnastics", icon: "human-handsup", defaultTime: "10:00 AM", timeSlot: "morning", group: "Movement / Fitness" },
  { key: "jumping_jacks", habitName: "Jumping Jacks", label: "Do jumping jacks", icon: "human-jump", defaultTime: "07:00 AM", timeSlot: "morning", group: "Movement / Fitness" },
  { key: "burpees", habitName: "Burpees", label: "Do burpees", icon: "human-handsup", defaultTime: "07:10 AM", timeSlot: "morning", group: "Movement / Fitness" },
  { key: "walk_the_dog", habitName: "Walk the Dog", label: "Walk your dog", icon: "dog", defaultTime: "07:30 AM", timeSlot: "morning", group: "Movement / Fitness" },
  { key: "skiing", habitName: "Skiing", label: "Go skiing", icon: "ski", defaultTime: "11:00 AM", timeSlot: "morning", group: "Movement / Fitness" },
  { key: "rowing", habitName: "Rowing", label: "Rowing workout", icon: "kayak", defaultTime: "08:00 AM", timeSlot: "morning", group: "Movement / Fitness" },
  { key: "parcours", habitName: "Parcours", label: "Parcours training", icon: "run-fast", defaultTime: "10:00 AM", timeSlot: "morning", group: "Movement / Fitness" },
  { key: "standup_paddle", habitName: "Standup Paddle", label: "Do standup paddle", icon: "kayak", defaultTime: "09:00 AM", timeSlot: "morning", group: "Movement / Fitness" },
  { key: "handstand", habitName: "Handstand", label: "Practice handstand", icon: "human-handsup", defaultTime: "08:00 PM", timeSlot: "evening", group: "Movement / Fitness" },
  { key: "park_workout", habitName: "Park Workout", label: "Outdoor workout", icon: "tree", defaultTime: "06:00 PM", timeSlot: "evening", group: "Movement / Fitness" },

  // ---------------- HEALTH / NUTRITION ----------------
  { key: "drink_water", habitName: "Drink Water", label: "Drink a glass of water", icon: "cup", defaultTime: "08:00 AM", timeSlot: "morning", group: "Health / Nutrition" },
  { key: "drink_tea", habitName: "Drink Tea", label: "Drink tea", icon: "tea", defaultTime: "04:00 PM", timeSlot: "afternoon", group: "Health / Nutrition" },
  { key: "drink_coffee", habitName: "Drink Coffee", label: "Drink coffee", icon: "coffee", defaultTime: "09:00 AM", timeSlot: "morning", group: "Health / Nutrition" },
  { key: "eat_breakfast", habitName: "Eat Breakfast", label: "Have breakfast", icon: "food-variant", defaultTime: "08:00 AM", timeSlot: "morning", group: "Health / Nutrition" },
  { key: "eat_lunch", habitName: "Eat Lunch", label: "Have lunch", icon: "food", defaultTime: "01:00 PM", timeSlot: "afternoon", group: "Health / Nutrition" },
  { key: "eat_dinner", habitName: "Eat Dinner", label: "Have dinner", icon: "food", defaultTime: "08:00 PM", timeSlot: "night", group: "Health / Nutrition" },
  { key: "eat_snack", habitName: "Eat Snack", label: "Healthy snack time", icon: "food", defaultTime: "04:00 PM", timeSlot: "afternoon", group: "Health / Nutrition" },
  { key: "eat_fruit", habitName: "Eat Fruit", label: "Eat some fruit", icon: "apple", defaultTime: "11:00 AM", timeSlot: "morning", group: "Health / Nutrition" },
  { key: "eat_vegetables", habitName: "Eat Vegetables", label: "Eat vegetables", icon: "carrot", defaultTime: "01:00 PM", timeSlot: "afternoon", group: "Health / Nutrition" },
  { key: "no_junk_food", habitName: "No Junk Food", label: "Avoid junk food", icon: "food-off-outline", defaultTime: "12:00 AM", timeSlot: "night", group: "Health / Nutrition" },
  { key: "cook_at_home", habitName: "Cook at Home", label: "Cook a meal at home", icon: "stove", defaultTime: "07:00 PM", timeSlot: "evening", group: "Health / Nutrition" },
  { key: "meal_prep", habitName: "Meal Prep", label: "Prep meals", icon: "food-container", defaultTime: "04:00 PM", timeSlot: "afternoon", group: "Health / Nutrition" },
  { key: "take_vitamins", habitName: "Take Vitamins", label: "Take vitamins", icon: "pill", defaultTime: "09:00 AM", timeSlot: "morning", group: "Health / Nutrition" },
  { key: "brush_teeth", habitName: "Brush Teeth", label: "Brush your teeth", icon: "toothbrush", defaultTime: "10:00 PM", timeSlot: "night", group: "Health / Nutrition" },
  { key: "floss_teeth", habitName: "Floss Teeth", label: "Floss your teeth", icon: "tooth", defaultTime: "10:00 PM", timeSlot: "night", group: "Health / Nutrition" },
  { key: "skincare_routine", habitName: "Skincare Routine", label: "Do skincare routine", icon: "face-woman", defaultTime: "10:30 PM", timeSlot: "night", group: "Health / Nutrition" },
  { key: "weigh_yourself", habitName: "Weigh Yourself", label: "Check your weight", icon: "scale-bathroom", defaultTime: "08:00 AM", timeSlot: "morning", group: "Health / Nutrition" },
  { key: "track_calories", habitName: "Track Calories", label: "Log your calories", icon: "calculator", defaultTime: "09:00 PM", timeSlot: "night", group: "Health / Nutrition" },
  { key: "eat_whole_grains", habitName: "Eat Whole Grains", label: "Whole grain meal", icon: "bread", defaultTime: "12:00 PM", timeSlot: "afternoon", group: "Health / Nutrition" },
  { key: "eat_protein", habitName: "Eat Protein", label: "Consume protein-rich food", icon: "egg", defaultTime: "12:00 PM", timeSlot: "afternoon", group: "Health / Nutrition" },
  { key: "avoid_sugar", habitName: "Avoid Sugar", label: "Avoid sugary foods", icon: "food-off-outline", defaultTime: "06:00 PM", timeSlot: "evening", group: "Health / Nutrition" },
  { key: "hydrate_regularly", habitName: "Hydrate Regularly", label: "Drink water through the day", icon: "glass", defaultTime: "11:00 AM", timeSlot: "morning", group: "Health / Nutrition" },
  { key: "eat_nuts", habitName: "Eat Nuts", label: "Eat a handful of nuts", icon: "nut", defaultTime: "12:00 PM", timeSlot: "afternoon", group: "Health / Nutrition" },
  { key: "eat_salad", habitName: "Eat Salad", label: "Eat salad", icon: "leaf", defaultTime: "01:00 PM", timeSlot: "afternoon", group: "Health / Nutrition" },
  { key: "fermented_food", habitName: "Eat Fermented Food", label: "Eat fermented foods (yogurt etc.)", icon: "bowl-mix", defaultTime: "07:00 PM", timeSlot: "evening", group: "Health / Nutrition" },
  { key: "drink_smoothie", habitName: "Drink Smoothie", label: "Drink a smoothie", icon: "cup", defaultTime: "10:00 AM", timeSlot: "morning", group: "Health / Nutrition" },
  { key: "eat_fish", habitName: "Eat Fish", label: "Eat fish meal", icon: "fish", defaultTime: "12:00 PM", timeSlot: "afternoon", group: "Health / Nutrition" },
  { key: "meal_log", habitName: "Meal Log", label: "Log meals for the day", icon: "clipboard-text", defaultTime: "07:00 PM", timeSlot: "evening", group: "Health / Nutrition" },

  // ---------------- SLEEP & RECOVERY ----------------
  { key: "go_to_bed_early", habitName: "Go to Bed Early", label: "Sleep early", icon: "bed", defaultTime: "10:00 PM", timeSlot: "night", group: "Sleep & Recovery" },
  { key: "wake_up_early", habitName: "Wake Up Early", label: "Wake up early", icon: "alarm", defaultTime: "06:00 AM", timeSlot: "morning", group: "Sleep & Recovery" },
  { key: "power_nap", habitName: "Power Nap", label: "Take a power nap", icon: "sleep", defaultTime: "02:00 PM", timeSlot: "afternoon", group: "Sleep & Recovery" },
  { key: "full_sleep", habitName: "Get Full Sleep", label: "Get 8 hours of sleep", icon: "sleep", defaultTime: "11:00 PM", timeSlot: "night", group: "Sleep & Recovery" },
  { key: "avoid_screen_night", habitName: "No Screen Night", label: "No screens before bed", icon: "cellphone-off", defaultTime: "09:30 PM", timeSlot: "night", group: "Sleep & Recovery" },
  { key: "night_routine", habitName: "Night Routine", label: "Do night routine", icon: "spa", defaultTime: "09:00 PM", timeSlot: "night", group: "Sleep & Recovery" },
  { key: "morning_routine", habitName: "Morning Routine", label: "Morning routine tasks", icon: "sun-rise", defaultTime: "06:30 AM", timeSlot: "morning", group: "Sleep & Recovery" },
  { key: "set_alarm", habitName: "Set Alarm", label: "Set your alarm", icon: "alarm-bell", defaultTime: "09:00 PM", timeSlot: "night", group: "Sleep & Recovery" },
  { key: "sleep_stretch", habitName: "Stretch Before Sleep", label: "Stretch before sleep", icon: "human-handsup", defaultTime: "10:00 PM", timeSlot: "night", group: "Sleep & Recovery" },
  { key: "power_down", habitName: "Power Down", label: "Shut down devices", icon: "cellphone-off", defaultTime: "09:00 PM", timeSlot: "night", group: "Sleep & Recovery" },
  { key: "white_noise", habitName: "White Noise", label: "Play white noise", icon: "volume-high", defaultTime: "09:00 PM", timeSlot: "night", group: "Sleep & Recovery" },
  { key: "dream_journal", habitName: "Dream Journal", label: "Log dreams upon waking", icon: "notebook", defaultTime: "06:00 AM", timeSlot: "morning", group: "Sleep & Recovery" },

  // ---------------- LEARNING / MENTAL ----------------
  { key: "reading", habitName: "Reading", label: "Read a book", icon: "book-open-page-variant", defaultTime: "09:00 PM", timeSlot: "night", group: "Learning / Mental" },
  { key: "study", habitName: "Study", label: "Study session", icon: "school", defaultTime: "07:00 PM", timeSlot: "evening", group: "Learning / Mental" },
  { key: "online_course", habitName: "Online Course", label: "Take an online course", icon: "laptop", defaultTime: "07:30 PM", timeSlot: "evening", group: "Learning / Mental" },
  { key: "language_learning", habitName: "Language Learning", label: "Practice a language", icon: "translate", defaultTime: "08:00 PM", timeSlot: "evening", group: "Learning / Mental" },
  { key: "journal", habitName: "Journal", label: "Write in your journal", icon: "notebook", defaultTime: "09:30 PM", timeSlot: "night", group: "Learning / Mental" },
  { key: "gratitude_journal", habitName: "Gratitude Journal", label: "Write gratitude entries", icon: "notebook-heart", defaultTime: "09:30 PM", timeSlot: "night", group: "Learning / Mental" },
  { key: "planning_day", habitName: "Planning Day", label: "Plan your day", icon: "calendar-check", defaultTime: "08:00 AM", timeSlot: "morning", group: "Learning / Mental" },
  { key: "coding_practice", habitName: "Coding Practice", label: "Practice coding", icon: "code-tags", defaultTime: "08:00 PM", timeSlot: "evening", group: "Learning / Mental" },
  { key: "music_practice", habitName: "Music Practice", label: "Practice music", icon: "music", defaultTime: "07:00 PM", timeSlot: "evening", group: "Learning / Mental" },
  { key: "draw_paint", habitName: "Draw or Paint", label: "Draw or paint", icon: "brush", defaultTime: "07:10 PM", timeSlot: "evening", group: "Learning / Mental" },
  { key: "play_instrument", habitName: "Play Instrument", label: "Play an instrument", icon: "guitar-acoustic", defaultTime: "07:15 PM", timeSlot: "evening", group: "Learning / Mental" },
  { key: "chess_practice", habitName: "Chess Practice", label: "Practice chess", icon: "chess-king", defaultTime: "06:00 PM", timeSlot: "evening", group: "Learning / Mental" },
  { key: "puzzle_solving", habitName: "Puzzle Solving", label: "Solve puzzles", icon: "puzzle", defaultTime: "03:00 PM", timeSlot: "afternoon", group: "Learning / Mental" },
  { key: "research_topic", habitName: "Research Topic", label: "Research new topics", icon: "search-web", defaultTime: "04:00 PM", timeSlot: "afternoon", group: "Learning / Mental" },
  { key: "memorize", habitName: "Memorize Something", label: "Memorize new information", icon: "brain", defaultTime: "07:00 PM", timeSlot: "evening", group: "Learning / Mental" },
  { key: "watch_documentary", habitName: "Watch Documentary", label: "Watch a documentary", icon: "movie", defaultTime: "08:00 PM", timeSlot: "evening", group: "Learning / Mental" },
  { key: "flashcards", habitName: "Flashcards Practice", label: "Review flashcards", icon: "cards", defaultTime: "07:00 PM", timeSlot: "evening", group: "Learning / Mental" },
  { key: "mental_math", habitName: "Mental Math", label: "Do mental math practice", icon: "calculator", defaultTime: "08:00 AM", timeSlot: "morning", group: "Learning / Mental" },
  { key: "visualization", habitName: "Visualization", label: "Visualize your goals", icon: "eye", defaultTime: "09:00 PM", timeSlot: "night", group: "Learning / Mental" },

  // ---------------- WORK / PRODUCTIVITY ----------------
  { key: "deep_work", habitName: "Deep Work", label: "Focus deep work session", icon: "briefcase-clock", defaultTime: "10:00 AM", timeSlot: "morning", group: "Work / Productivity" },
  { key: "no_phone_distraction", habitName: "No Phone Distraction", label: "Avoid phone distractions", icon: "cellphone-off", defaultTime: "10:00 AM", timeSlot: "morning", group: "Work / Productivity" },
  { key: "check_email_once", habitName: "Check Email Once", label: "Only check email once", icon: "email", defaultTime: "11:00 AM", timeSlot: "morning", group: "Work / Productivity" },
  { key: "daily_review", habitName: "Daily Review", label: "Review your day", icon: "clipboard-text", defaultTime: "09:00 PM", timeSlot: "night", group: "Work / Productivity" },
  { key: "clean_desk", habitName: "Clean Desk", label: "Clean your desk", icon: "desk", defaultTime: "06:00 PM", timeSlot: "evening", group: "Work / Productivity" },
  { key: "organize_files", habitName: "Organize Files", label: "Organize computer files", icon: "folder", defaultTime: "08:00 PM", timeSlot: "evening", group: "Work / Productivity" },
  { key: "clear_inbox", habitName: "Clear Inbox", label: "Inbox zero", icon: "inbox", defaultTime: "07:00 PM", timeSlot: "evening", group: "Work / Productivity" },
  { key: "write_report", habitName: "Write Report", label: "Write your report", icon: "file-document", defaultTime: "05:00 PM", timeSlot: "evening", group: "Work / Productivity" },
  { key: "sync_calendar", habitName: "Sync Calendar", label: "Sync calendar", icon: "calendar-sync", defaultTime: "08:00 AM", timeSlot: "morning", group: "Work / Productivity" },
  { key: "backup_files", habitName: "Backup Files", label: "Backup important files", icon: "cloud-upload", defaultTime: "09:00 PM", timeSlot: "night", group: "Work / Productivity" },
  { key: "focus_block", habitName: "Focus Block", label: "Start focus block", icon: "timer", defaultTime: "09:00 AM", timeSlot: "morning", group: "Work / Productivity" },
  { key: "meeting_prep", habitName: "Meeting Prep", label: "Prepare for meeting", icon: "account-group", defaultTime: "09:30 AM", timeSlot: "morning", group: "Work / Productivity" },
  { key: "review_goals", habitName: "Review Goals", label: "Review weekly goals", icon: "target", defaultTime: "08:00 PM", timeSlot: "evening", group: "Work / Productivity" },

  // ---------------- HOUSEHOLD / CHORES ----------------
  { key: "clean_room", habitName: "Clean Room", label: "Clean your room", icon: "broom", defaultTime: "05:00 PM", timeSlot: "evening", group: "Household / Chores" },
  { key: "do_laundry", habitName: "Do Laundry", label: "Do the laundry", icon: "washing-machine", defaultTime: "03:00 PM", timeSlot: "afternoon", group: "Household / Chores" },
  { key: "wash_dishes", habitName: "Wash Dishes", label: "Wash the dishes", icon: "dishwasher", defaultTime: "08:30 PM", timeSlot: "night", group: "Household / Chores" },
  { key: "make_bed", habitName: "Make Bed", label: "Make your bed", icon: "bed-king", defaultTime: "08:00 AM", timeSlot: "morning", group: "Household / Chores" },
  { key: "take_out_trash", habitName: "Take Out Trash", label: "Take out the trash", icon: "trash-can", defaultTime: "08:00 PM", timeSlot: "night", group: "Household / Chores" },
  { key: "grocery_shopping", habitName: "Grocery Shopping", label: "Do grocery shopping", icon: "cart", defaultTime: "04:00 PM", timeSlot: "afternoon", group: "Household / Chores" },
  { key: "water_plants", habitName: "Water Plants", label: "Water your plants", icon: "watering-can", defaultTime: "09:00 AM", timeSlot: "morning", group: "Household / Chores" },
  { key: "pet_care", habitName: "Pet Care", label: "Care for your pet", icon: "dog", defaultTime: "07:00 PM", timeSlot: "evening", group: "Household / Chores" },
  { key: "vacuum_house", habitName: "Vacuum House", label: "Vacuum the house", icon: "vacuum", defaultTime: "06:00 PM", timeSlot: "evening", group: "Household / Chores" },
  { key: "clean_bathroom", habitName: "Clean Bathroom", label: "Clean bathroom", icon: "shower", defaultTime: "04:00 PM", timeSlot: "afternoon", group: "Household / Chores" },
  { key: "dust_furniture", habitName: "Dust Furniture", label: "Dust furniture", icon: "sofa", defaultTime: "07:30 PM", timeSlot: "evening", group: "Household / Chores" },
  { key: "organize_closet", habitName: "Organize Closet", label: "Organize closet", icon: "hanger", defaultTime: "03:00 PM", timeSlot: "afternoon", group: "Household / Chores" },
  { key: "wash_windows", habitName: "Wash Windows", label: "Clean windows", icon: "window-clean", defaultTime: "10:00 AM", timeSlot: "morning", group: "Household / Chores" },
  { key: "mop_floor", habitName: "Mop Floor", label: "Mop the floors", icon: "mop", defaultTime: "06:00 PM", timeSlot: "evening", group: "Household / Chores" },
  { key: "clean_fridge", habitName: "Clean Fridge", label: "Clean refrigerator", icon: "fridge-outline", defaultTime: "01:00 PM", timeSlot: "afternoon", group: "Household / Chores" },
  { key: "sort_mail", habitName: "Sort Mail", label: "Sort mail", icon: "email", defaultTime: "05:00 PM", timeSlot: "evening", group: "Household / Chores" },
  { key: "declutter", habitName: "Declutter", label: "Declutter home", icon: "cube-send", defaultTime: "06:00 PM", timeSlot: "evening", group: "Household / Chores" },
  { key: "wash_car", habitName: "Wash Car", label: "Wash your car", icon: "car-wash", defaultTime: "10:00 AM", timeSlot: "morning", group: "Household / Chores" },
  { key: "change_sheets", habitName: "Change Sheets", label: "Change your bedsheets", icon: "bed-single", defaultTime: "03:00 PM", timeSlot: "afternoon", group: "Household / Chores" },
  { key: "empty_dishwasher", habitName: "Empty Dishwasher", label: "Unload dishwasher", icon: "dishwasher", defaultTime: "08:30 PM", timeSlot: "night", group: "Household / Chores" },

  // ---------------- SOCIAL / FAMILY ----------------
  { key: "call_family", habitName: "Call Family", label: "Call a family member", icon: "phone", defaultTime: "08:00 PM", timeSlot: "evening", group: "Social / Family" },
  { key: "meet_friend", habitName: "Meet Friend", label: "Meet a friend", icon: "account-group", defaultTime: "06:00 PM", timeSlot: "evening", group: "Social / Family" },
  { key: "play_with_kids", habitName: "Play with Kids", label: "Play with your kids", icon: "baby-face-outline", defaultTime: "06:00 PM", timeSlot: "evening", group: "Social / Family" },
  { key: "date_night", habitName: "Date Night", label: "Go on a date night", icon: "heart-outline", defaultTime: "08:00 PM", timeSlot: "night", group: "Social / Family" },
  { key: "cook_with_family", habitName: "Cook with Family", label: "Cook a meal with family", icon: "stove", defaultTime: "07:00 PM", timeSlot: "evening", group: "Social / Family" },
  { key: "eat_together", habitName: "Eat Together", label: "Eat dinner together", icon: "food", defaultTime: "08:00 PM", timeSlot: "night", group: "Social / Family" },
  { key: "story_time", habitName: "Story Time", label: "Read stories together", icon: "book-open-page-variant", defaultTime: "08:30 PM", timeSlot: "night", group: "Social / Family" },
  { key: "board_games", habitName: "Board Games", label: "Play board games", icon: "dice-multiple", defaultTime: "07:00 PM", timeSlot: "evening", group: "Social / Family" },
  { key: "family_walk", habitName: "Family Walk", label: "Walk with family", icon: "walk", defaultTime: "06:00 PM", timeSlot: "evening", group: "Social / Family" },
  { key: "send_message", habitName: "Send Message", label: "Send a positive message", icon: "message", defaultTime: "08:00 PM", timeSlot: "evening", group: "Social / Family" },
  { key: "family_game", habitName: "Family Game", label: "Play a family game", icon: "gamepad-variant", defaultTime: "07:00 PM", timeSlot: "evening", group: "Social / Family" },
  { key: "celebrate", habitName: "Celebrate Small Wins", label: "Celebrate a win", icon: "star", defaultTime: "08:30 PM", timeSlot: "night", group: "Social / Family" },

  // ---------------- MINDFULNESS / SELF-CARE ----------------
  { key: "meditate", habitName: "Meditate", label: "Meditate", icon: "meditation", defaultTime: "09:00 PM", timeSlot: "night", group: "Mindfulness / Self-care" },
  { key: "breathing_exercise", habitName: "Breathing Exercise", label: "Do breathing exercises", icon: "weather-windy", defaultTime: "09:00 AM", timeSlot: "morning", group: "Mindfulness / Self-care" },
  { key: "gratitude_practice", habitName: "Gratitude Practice", label: "Practice gratitude", icon: "notebook-heart", defaultTime: "09:30 PM", timeSlot: "night", group: "Mindfulness / Self-care" },
  { key: "digital_detox", habitName: "Digital Detox", label: "Digital detox (no screens)", icon: "cellphone-off", defaultTime: "08:00 PM", timeSlot: "night", group: "Mindfulness / Self-care" },
  { key: "walk_in_nature", habitName: "Walk in Nature", label: "Walk in nature", icon: "pine-tree", defaultTime: "05:00 PM", timeSlot: "evening", group: "Mindfulness / Self-care" },
  { key: "affirmations", habitName: "Affirmations", label: "Say positive affirmations", icon: "comment-check", defaultTime: "07:00 AM", timeSlot: "morning", group: "Mindfulness / Self-care" },
  { key: "self_compassion", habitName: "Self Compassion", label: "Practice self-compassion", icon: "face-man", defaultTime: "10:00 PM", timeSlot: "night", group: "Mindfulness / Self-care" },
  { key: "mindful_eating", habitName: "Mindful Eating", label: "Eat mindfully", icon: "food-variant", defaultTime: "01:00 PM", timeSlot: "afternoon", group: "Mindfulness / Self-care" },
  { key: "body_scan", habitName: "Body Scan", label: "Body scan meditation", icon: "human-scanner", defaultTime: "08:30 PM", timeSlot: "night", group: "Mindfulness / Self-care" },
  { key: "hot_bath", habitName: "Hot Bath", label: "Take a hot bath", icon: "bathtub", defaultTime: "08:00 PM", timeSlot: "night", group: "Mindfulness / Self-care" },
  { key: "self_reflection", habitName: "Self Reflection", label: "Reflect on your day", icon: "mirror", defaultTime: "09:00 PM", timeSlot: "night", group: "Mindfulness / Self-care" },
  { key: "read_affirmation", habitName: "Read Affirmation", label: "Read daily affirmation", icon: "book-open-page-variant", defaultTime: "06:00 AM", timeSlot: "morning", group: "Mindfulness / Self-care" },

  // ---------------- FINANCE & ADMIN ----------------
  { key: "track_expenses", habitName: "Track Expenses", label: "Track your expenses", icon: "calculator", defaultTime: "08:00 PM", timeSlot: "evening", group: "Finance / Admin" },
  { key: "budget_review", habitName: "Budget Review", label: "Review your budget", icon: "chart-line", defaultTime: "08:30 PM", timeSlot: "evening", group: "Finance / Admin" },
  { key: "check_investments", habitName: "Check Investments", label: "Check your investments", icon: "finance", defaultTime: "08:00 PM", timeSlot: "evening", group: "Finance / Admin" },
  { key: "pay_bills", habitName: "Pay Bills", label: "Pay your bills", icon: "invoice", defaultTime: "07:00 PM", timeSlot: "evening", group: "Finance / Admin" },
  { key: "review_transactions", habitName: "Review Transactions", label: "Review transactions", icon: "bank", defaultTime: "08:45 PM", timeSlot: "night", group: "Finance / Admin" },
  { key: "check_credit_score", habitName: "Check Credit Score", label: "Check your credit score", icon: "credit-card", defaultTime: "11:00 AM", timeSlot: "morning", group: "Finance / Admin" },
  { key: "pay_debt", habitName: "Pay Debt", label: "Pay off debts", icon: "currency-usd", defaultTime: "06:00 PM", timeSlot: "evening", group: "Finance / Admin" },
  { key: "save_money", habitName: "Save Money", label: "Save some money", icon: "bank", defaultTime: "08:00 PM", timeSlot: "evening", group: "Finance / Admin" },
  { key: "expense_report", habitName: "Expense Report", label: "File expense report", icon: "file-document", defaultTime: "07:00 PM", timeSlot: "evening", group: "Finance / Admin" },
  { key: "scan_receipts", habitName: "Scan Receipts", label: "Scan receipts", icon: "barcode-scan", defaultTime: "08:45 PM", timeSlot: "night", group: "Finance / Admin" },
  { key: "donate", habitName: "Donate", label: "Donate to charity", icon: "hand-heart", defaultTime: "02:00 PM", timeSlot: "afternoon", group: "Finance / Admin" },

  // ---------------- CREATIVE / HOBBIES ----------------
  { key: "photography_practice", habitName: "Photography Practice", label: "Practice photography", icon: "camera", defaultTime: "05:00 PM", timeSlot: "evening", group: "Creative / Hobbies" },
  { key: "video_editing", habitName: "Video Editing", label: "Edit videos", icon: "video", defaultTime: "08:00 PM", timeSlot: "evening", group: "Creative / Hobbies" },
  { key: "gaming", habitName: "Gaming", label: "Play video games", icon: "gamepad-variant", defaultTime: "09:00 PM", timeSlot: "night", group: "Creative / Hobbies" },
  { key: "cooking_practice", habitName: "Cooking Practice", label: "Practice cooking", icon: "chef-hat", defaultTime: "07:00 PM", timeSlot: "evening", group: "Creative / Hobbies" },
  { key: "baking", habitName: "Baking", label: "Bake something", icon: "cupcake", defaultTime: "03:00 PM", timeSlot: "afternoon", group: "Creative / Hobbies" },
  { key: "gardening", habitName: "Gardening", label: "Do gardening", icon: "flower", defaultTime: "04:00 PM", timeSlot: "afternoon", group: "Creative / Hobbies" },
  { key: "art_practice", habitName: "Art Practice", label: "Practice art", icon: "palette", defaultTime: "07:00 PM", timeSlot: "evening", group: "Creative / Hobbies" },
  { key: "lego_building", habitName: "Lego Building", label: "Build with Legos", icon: "cube-outline", defaultTime: "06:00 PM", timeSlot: "evening", group: "Creative / Hobbies" },
  { key: "crafts", habitName: "Crafts", label: "Do crafts", icon: "tools", defaultTime: "05:00 PM", timeSlot: "evening", group: "Creative / Hobbies" },
  { key: "woodworking", habitName: "Woodworking", label: "Woodworking project", icon: "saw-blade", defaultTime: "02:00 PM", timeSlot: "afternoon", group: "Creative / Hobbies" },
  { key: "scrapbooking", habitName: "Scrapbooking", label: "Do scrapbooking", icon: "book-open-page-variant", defaultTime: "03:00 PM", timeSlot: "afternoon", group: "Creative / Hobbies" },
  { key: "writing_poetry", habitName: "Write Poetry", label: "Write poetry", icon: "feather", defaultTime: "09:00 PM", timeSlot: "night", group: "Creative / Hobbies" },
  { key: "paint_miniatures", habitName: "Paint Miniatures", label: "Paint miniatures", icon: "palette", defaultTime: "07:00 PM", timeSlot: "evening", group: "Creative / Hobbies" },
  { key: "write_blog", habitName: "Write Blog", label: "Write a blog post", icon: "typewriter", defaultTime: "09:00 PM", timeSlot: "night", group: "Creative / Hobbies" },
  { key: "knitting", habitName: "Knitting", label: "Knit something", icon: "yarn", defaultTime: "03:00 PM", timeSlot: "afternoon", group: "Creative / Hobbies" },
  { key: "origami", habitName: "Origami", label: "Practice origami", icon: "fold", defaultTime: "01:00 PM", timeSlot: "afternoon", group: "Creative / Hobbies" },

  // ---------------- COMMUTE / ERRANDS ----------------
  { key: "bike_to_work", habitName: "Bike to Work", label: "Commute by bike", icon: "bike", defaultTime: "08:00 AM", timeSlot: "morning", group: "Commute / Errands" },
  { key: "walk_to_work", habitName: "Walk to Work", label: "Walk to work", icon: "walk", defaultTime: "08:00 AM", timeSlot: "morning", group: "Commute / Errands" },
  { key: "public_transport", habitName: "Public Transport", label: "Use public transport", icon: "train", defaultTime: "08:30 AM", timeSlot: "morning", group: "Commute / Errands" },
  { key: "errand_run", habitName: "Run Errands", label: "Run essential errands", icon: "car", defaultTime: "01:00 PM", timeSlot: "afternoon", group: "Commute / Errands" },
  { key: "drop_package", habitName: "Drop Package", label: "Drop a package", icon: "package", defaultTime: "03:00 PM", timeSlot: "afternoon", group: "Commute / Errands" },
  { key: "fill_gas", habitName: "Fill Gas Tank", label: "Fill your gas tank", icon: "gas-station", defaultTime: "04:30 PM", timeSlot: "afternoon", group: "Commute / Errands" },
  { key: "maintenance_car", habitName: "Car Maintenance", label: "Maintain your car", icon: "car-cog", defaultTime: "10:00 AM", timeSlot: "morning", group: "Commute / Errands" },
  { key: "book_appointment", habitName: "Book Appointment", label: "Book an appointment", icon: "calendar-check", defaultTime: "09:00 AM", timeSlot: "morning", group: "Commute / Errands" },
  { key: "collect_parcel", habitName: "Collect Parcel", label: "Collect parcel", icon: "package", defaultTime: "05:00 PM", timeSlot: "evening", group: "Commute / Errands" },
  { key: "return_items", habitName: "Return Items", label: "Return purchased items", icon: "cube-send", defaultTime: "12:00 PM", timeSlot: "afternoon", group: "Commute / Errands" },

  // ---------------- FAITH / SPIRITUAL (ISLAMIC + more) ----------------
  { key: "fajr", habitName: "Fajr Prayer", label: "Perform Fajr prayer", icon: "hands-pray", defaultTime: "05:30 AM", timeSlot: "morning", group: "Faith / Spiritual" },
  { key: "dhuhr", habitName: "Dhuhr Prayer", label: "Perform Dhuhr prayer", icon: "hands-pray", defaultTime: "01:30 PM", timeSlot: "afternoon", group: "Faith / Spiritual" },
  { key: "asr", habitName: "Asr Prayer", label: "Perform Asr prayer", icon: "hands-pray", defaultTime: "04:30 PM", timeSlot: "afternoon", group: "Faith / Spiritual" },
  { key: "maghrib", habitName: "Maghrib Prayer", label: "Perform Maghrib prayer", icon: "hands-pray", defaultTime: "06:30 PM", timeSlot: "evening", group: "Faith / Spiritual" },
  { key: "isha", habitName: "Isha Prayer", label: "Perform Isha prayer", icon: "hands-pray", defaultTime: "08:30 PM", timeSlot: "night", group: "Faith / Spiritual" },
  { key: "tahajjud", habitName: "Tahajjud Prayer", label: "Perform Tahajjud prayer", icon: "hands-pray", defaultTime: "03:00 AM", timeSlot: "night", group: "Faith / Spiritual" },
  { key: "duha", habitName: "Duha Prayer", label: "Pray Duha", icon: "hands-pray", defaultTime: "09:00 AM", timeSlot: "morning", group: "Faith / Spiritual" },
  { key: "witr", habitName: "Witr Prayer", label: "Perform Witr prayer", icon: "hands-pray", defaultTime: "09:45 PM", timeSlot: "night", group: "Faith / Spiritual" },
  { key: "read_quran", habitName: "Read Quran", label: "Read Quran", icon: "book-cross", defaultTime: "07:00 AM", timeSlot: "morning", group: "Faith / Spiritual" },
  { key: "dua", habitName: "Dua", label: "Make dua prayers", icon: "hands-pray", defaultTime: "06:00 PM", timeSlot: "evening", group: "Faith / Spiritual" },
  { key: "dhikr", habitName: "Dhikr", label: "Perform dhikr/remembrance", icon: "repeat", defaultTime: "06:30 PM", timeSlot: "evening", group: "Faith / Spiritual" },
  { key: "friday_prayer", habitName: "Friday Prayer", label: "Attend Jumu'ah (Friday prayer)", icon: "hands-pray", defaultTime: "01:30 PM", timeSlot: "afternoon", group: "Faith / Spiritual" },
  { key: "charity", habitName: "Charity (Sadaqah)", label: "Give charity", icon: "hand-heart", defaultTime: "02:00 PM", timeSlot: "afternoon", group: "Faith / Spiritual" },
  { key: "help_others", habitName: "Help Others", label: "Help someone today", icon: "handshake", defaultTime: "01:00 PM", timeSlot: "afternoon", group: "Faith / Spiritual" },
  { key: "read_scripture", habitName: "Read Scripture", label: "Read scripture", icon: "book-cross", defaultTime: "09:00 PM", timeSlot: "night", group: "Faith / Spiritual" },
  { key: "istikhara", habitName: "Istikhara Prayer", label: "Perform Istikhara prayer", icon: "hands-pray", defaultTime: "09:30 PM", timeSlot: "night", group: "Faith / Spiritual" },
  { key: "send_salawat", habitName: "Send Salawat", label: "Send blessings on Prophet", icon: "heart", defaultTime: "09:00 AM", timeSlot: "morning", group: "Faith / Spiritual" },
  { key: "make_wudu", habitName: "Make Wudu", label: "Perform ablution (wudu)", icon: "water", defaultTime: "05:20 AM", timeSlot: "morning", group: "Faith / Spiritual" },
  { key: "help_mosque", habitName: "Help at Mosque", label: "Assist mosque duties", icon: "mosque", defaultTime: "12:00 PM", timeSlot: "afternoon", group: "Faith / Spiritual" },
  { key: "feed_fast", habitName: "Feed During Fast", label: "Feed a fasting person", icon: "food-variant", defaultTime: "06:30 PM", timeSlot: "evening", group: "Faith / Spiritual" },
  { key: "taraweeh", habitName: "Taraweeh Prayer", label: "Perform Taraweeh prayer", icon: "hands-pray", defaultTime: "09:30 PM", timeSlot: "night", group: "Faith / Spiritual" },
  { key: "qiyam", habitName: "Qiyam Al-Layl", label: "Night prayer (Qiyam)", icon: "hands-pray", defaultTime: "02:00 AM", timeSlot: "night", group: "Faith / Spiritual" },
  { key: "eid_prayer", habitName: "Eid Prayer", label: "Perform Eid prayer", icon: "hands-pray", defaultTime: "07:30 AM", timeSlot: "morning", group: "Faith / Spiritual" },
  { key: "visit_graveyard", habitName: "Visit Graveyard", label: "Visit graveyard and pray", icon: "grave", defaultTime: "04:00 PM", timeSlot: "afternoon", group: "Faith / Spiritual" },
  { key: "learn_dua", habitName: "Learn Dua", label: "Learn new dua", icon: "hands-pray", defaultTime: "06:00 PM", timeSlot: "evening", group: "Faith / Spiritual" },
  { key: "teach_quran", habitName: "Teach Quran", label: "Teach Quran to someone", icon: "book-open-page-variant", defaultTime: "07:00 PM", timeSlot: "evening", group: "Faith / Spiritual" },
  { key: "help_neighbor", habitName: "Help Neighbor", label: "Help your neighbor", icon: "handshake", defaultTime: "01:00 PM", timeSlot: "afternoon", group: "Faith / Spiritual" },
  { key: "tasbeeh", habitName: "Count Tasbeeh", label: "Say tasbeeh (glorifications)", icon: "repeat", defaultTime: "09:00 AM", timeSlot: "morning", group: "Faith / Spiritual" },
  { key: "islamic_lecture", habitName: "Islamic Lecture", label: "Attend Islamic lecture", icon: "school", defaultTime: "07:00 PM", timeSlot: "evening", group: "Faith / Spiritual" },
  { key: "quran_memorization", habitName: "Quran Memorization", label: "Memorize Quran verses", icon: "book-cross", defaultTime: "09:00 AM", timeSlot: "morning", group: "Faith / Spiritual" },
  { key: "istighfar", habitName: "Istighfar", label: "Say istighfar (seek forgiveness)", icon: "hands-pray", defaultTime: "09:00 PM", timeSlot: "night", group: "Faith / Spiritual" },
  { key: "prophet_story", habitName: "Prophet's Story", label: "Read stories of prophets", icon: "book-open-page-variant", defaultTime: "08:00 PM", timeSlot: "evening", group: "Faith / Spiritual" },
  { key: "azkar_morning", habitName: "Azkar Morning", label: "Morning azkar recitation", icon: "repeat", defaultTime: "06:30 AM", timeSlot: "morning", group: "Faith / Spiritual" },
  { key: "azkar_evening", habitName: "Azkar Evening", label: "Evening azkar recitation", icon: "repeat", defaultTime: "05:30 PM", timeSlot: "evening", group: "Faith / Spiritual" },
  { key: "family_islamic", habitName: "Islamic Discussion", label: "Islamic discussion with family", icon: "account-group", defaultTime: "09:00 PM", timeSlot: "night", group: "Faith / Spiritual" },
  { key: "fast_voluntary", habitName: "Voluntary Fast", label: "Fast a voluntary day", icon: "food-off-outline", defaultTime: "06:00 AM", timeSlot: "morning", group: "Faith / Spiritual" },
  { key: "give_zakat", habitName: "Pay Zakat", label: "Pay zakat", icon: "currency-usd", defaultTime: "02:00 PM", timeSlot: "afternoon", group: "Faith / Spiritual" },
 
  // Christian
  { key: "morning_prayer_christian", habitName: "Morning Prayer (Christian)", label: "Say morning prayer", icon: "cross", defaultTime: "07:00 AM", timeSlot: "morning", group: "Faith / Spiritual" },
  { key: "read_bible", habitName: "Read Bible", label: "Read Bible", icon: "book-cross", defaultTime: "09:00 PM", timeSlot: "night", group: "Faith / Spiritual" },

  // Hindu
  { key: "aarti", habitName: "Aarti", label: "Perform Aarti rituals", icon: "fire", defaultTime: "07:00 PM", timeSlot: "evening", group: "Faith / Spiritual" },
  { key: "read_bhagavad_gita", habitName: "Read Bhagavad Gita", label: "Read Bhagavad Gita", icon: "book-open-page-variant", defaultTime: "08:00 PM", timeSlot: "evening", group: "Faith / Spiritual" },
];

(async () => {
  try {
    await mongoose.connect("mongodb://localhost:27017/streaksphere-dev");
    for (const h of HABIT_DEFS) {
      await Habit.updateOne({ key: h.key }, { $set: h }, { upsert: true });
    }
    console.log("Seeded predefined habits");
    process.exit(0);
  } catch (e) {
    console.error("Seed error", e);
    process.exit(1);
  }
})();